# Generated by Django 2.2.9 on 2020-01-19 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('contry_origin', models.CharField(max_length=100)),
                ('born', models.DateField()),
                ('died', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location_name', models.CharField(max_length=150)),
                ('contry', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('first_year', models.PositiveIntegerField()),
                ('last_year', models.PositiveIntegerField()),
                ('youtube_chanel', models.CharField(max_length=2048)),
                ('creator', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
