# Generated by Django 2.2.9 on 2020-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='festival',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
