# Generated by Django 2.2.9 on 2020-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200119_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='headliners',
            field=models.ManyToManyField(to='landing.Artist'),
        ),
    ]
