# Generated by Django 2.2.9 on 2020-01-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200119_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(default='Artist Image', upload_to='artists'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='picture',
            field=models.ImageField(default='Festival Image', upload_to='festivals'),
        ),
    ]
