# Generated by Django 2.2.9 on 2020-01-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20200119_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='picture',
        ),
    ]
