# Generated by Django 2.2.9 on 2020-01-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0007_auto_20200124_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='creator',
        ),
        migrations.AddField(
            model_name='artist',
            name='added_by',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='festival',
            name='added_by',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
